### ISSUE TITLE
upload组件上传返回数据 特殊字符转义问题

### ISSUE THREAD

**Issue by sammiewy** [regular-ui/regular-ui#14]
regular-ui 上传组件  返回的数据如果有&等符号 会被转义了\&amp; 
请求返回数据：
{
   code: 400,
   url: "http://xxxxxxxxxxxxxx?xxx=xxxx&xxx=xxxx&xxxx=xxxxxx"
}
处理后的数据：
 url: "http://xxxxxxxxxxxxxx?xxx=xxxx&amp;xxx=xxxx&amp;xxxx=xxxxxx"

**Comment by rainfore** [comment]
fixed
