### ISSUE TITLE
仓库命名规范？

### ISSUE THREAD

**Issue by leeluolee** [regular-ui/regular-ui#20]
比如我提供的并不是一个组件，而是一套指令或事件（独立的）。  该如何命名？

**Comment by z-ZYS-s** [comment]
一个仓库原则上可以包含一个或几个组件、指令或事件等，建议尽量将仓库粒子化，最相关的部分可以放在一个仓库里。

为了和npm包一致，仓库名全小写：
如果仓库以组件为主，则以ui-开头，如ui-listview，对应的npm包名：rgui-ui-listview；
如果仓库以指令为主，则以r-开头，如r-autofocus，对应的npm包名：rgui-r-focus；
如果仓库以过滤器为主，则以filter-开头，如filter-format，对应的npm包名：rgui-filter-format；
如果仓库以事件为主，则以on-开头，如on-clickout，对应的npm包名：rgui-on-clickout；
如果仓库以主题为主，则以theme-开头，如theme-bootstrap，对应的npm包名：rgui-theme-bootstrap；
