### ISSUE TITLE
Droppable组件模板中带有svg元素时，部分情况下不能正确渲染

### ISSUE THREAD

**Issue by hellozts4120** [regular-ui/regular-ui#22]
当Droppable组件模板中带有svg元素中的foreignObject，以及使用xlink:href注册图片文件路径的image元素时，不能正确渲染，希望能修复bug

**Comment by z-ZYS-s** [comment]
Why close?

**Comment by hellozts4120** [comment]
后来发现问题的根源是因为regular没有处理这几个属性的namespace，并不是ui出了问题，所以close了这个issue，非常抱歉！
