### ISSUE TITLE
treeView模块会修改传入进去的数据

### ISSUE THREAD

**Issue by lleohao** [regular-ui/regular-ui#28]
多个`treeView`传入相同的`source`时，所以`treeView`的开启状态会同步

控制台查看传入的`source`会看到数据被加上的`open`属性

**Comment by z-ZYS-s** [comment]
记住Regular是双向绑定，数据会更新UI，组件也有可能改变数据。不是给`treeView`传入了`source`，而且把`source`绑定在了`treeView`上。多个treeView用的同一份数据，表示把这些treeView都绑定起来了。
内部如果单独记录`open`的话，会很复杂，要同时维护两份数据，而且不止是`open`也可能是别的什么。
如果要分开，建议用个深度clone函数拷贝一下，或者保证每次绑定的时候`source`是重新产生的。

**Comment by lleohao** [comment]
OK 谢谢啦
