### ISSUE TITLE
Select2无法支持外部传入disabled

### ISSUE THREAD

**Issue by henryzp** [regular-ui/regular-ui#32]
[api](http://regular-ui.github.io/jsunit/select2.html)里面提及的

```
data.disabled 只能outer到inner
```

无法双向，导致在创建select2后，我想动态改变select的disable就比较麻烦。

我一开始的想法是让结构里面的ui，或者div，直接disabled。

但这样和之前的效果有差异。如果重新创建组件，个人感觉不是太合理。

有什么解决的方案吗？

**Comment by z-ZYS-s** [comment]
```
data.disabled 只能outer到inner
```

这个不是无法双向的意思，而且表示你可以设置disabled的值，并且组件内部没有操作修改这个值。你可以动态改disabled的值的。

另外就是div这种没有disabled属性。disabled只是让select方法return，并且加个class改个样式而已。

**Comment by henryzp** [comment]
具体怎么动态修改呢？

通过select2组件的data.disabled=false，并没有用

发自我的 iPad

**Comment by henryzp** [comment]
@rainfore 

可能是我没表达清楚，我的意思是select2这个component生成出来之后，

去修改component.data下面的什么属性，能让它disabled的，或者enabled

**Comment by z-ZYS-s** [comment]
双向绑定的方式

``` xml
<select2 disabled={select2Disabled} />
```

``` javascript
this.data.select2Disabled = true;
```

ref的方式

``` xml
<select2 ref="select2" />
```

``` javascript
this.$refs.select2.data.disabled = true;
```

如果你是通过$inject，要记得$update。

**Comment by henryzp** [comment]
@rainfore ，ok。。。不知道为什么你这个写法，我之前写过，但当时是报错的。。

可能我哪里写的有问题吧，这次是OK的。。

谢谢
