### ISSUE TITLE
r-model只能用在具体表单原件上么

### ISSUE THREAD

**Issue by chengmeng1117** [regular-ui/regular-ui#46]
如果我使用的是表单校验js模块
比如`<input2>`

这里就不能使用r-model了吧

**Comment by z-ZYS-s** [comment]
是的，`r-model`只能在原生DOM上使用，不能在组件上使用。

**Comment by chengmeng1117** [comment]
原来组件上的value就是r-model的实现啊

**Comment by z-ZYS-s** [comment]
差不多，一种是组件内部使用`r-model`，另一种是直接实现`r-model`功能
