### ISSUE TITLE
自定义样式表

### ISSUE THREAD

**Issue by chengmeng1117** [regular-ui/regular-ui#47]
想在各个组件的scss基础上做修改样式，然后编译成类似flat之类的一套样式表，来适应自己的网页风格，
可是编译的时候会有这样一个问题
很多 include的mixin都没有定义过，全局搜索也搜不到，这个是什么原因呀

**Comment by z-ZYS-s** [comment]
应该是在mass里面，有个[mass2scss](https://github.com/rainfore/mass2scss)
