### ISSUE TITLE
个别ui提供的快键方法无法extend

### ISSUE THREAD

**Issue by kidbear** [regular-ui/regular-ui#7]
Modal，Notify等组件提供了一些快捷方法，如alert,confirm,show等，无法被extend，不易于扩展，请修复~

**Comment by leeluolee** [comment]
这个你准备怎么改？   单独重写  Modal.extend?  Notify.extend?     @rainfore

**Comment by rainfore** [comment]
我还没想好

**Comment by rainfore** [comment]
Modal和Notify扩展的几个函数还是有区别的。改写Modal.extend很easy。但改写Notify.extend有这么个问题，Notify扩展的几个函数共用一个实例，具体扩展后想怎么使用我不是很清楚。
所以为了统一，目前不打算改写extend。

不过我把Modal.alert和Modal.confirm和Notify里方法稍微修改了一下，你扩展后少写代码。

```javascript
var TestModal = Modal.extend();
TestModal.alert = Modal.alert;
TestModal.confirm = Modal.confirm;

var TestNotify = Notify.extend();
var testNotify = new TestNotify();
Notify.METHODS.forEach(function(method) {
    TestNotify[method] = testNotify[method].bind(testNotify);
});
```

**Comment by rainfore** [comment]
下个版本（v0.1.7）发布。
